Add baseline risk metrics
UrbanInstitute/syntheval pull request #100
Opened 2024-09-27 11:56 UTC by jhseeman

Two notes here: 
1. Setting the base branch as `disc_qid_mi` until the base gets merged into `version0.0.4`
2. I am using the `twosamples` packages for lightweight and fast eCDF distance calculations. I have included it as a required dependency- please let me know if you have any concerns there.

2024-10-02 12:34 UTC, awunderground requested changes
Similar review as last time. I didn't find anything wrong but there are lots of opportunities to improve the clarity of the code.

2024-10-02 12:34 UTC, awunderground commented on R/disc_baseline.R
> +#' `"ad"` (Anderson-Darling), defaults, to `"ks"`.
Nice.

2024-10-02 12:34 UTC, awunderground commented on R/disc_baseline.R
> +  tclose_metric_numeric <- match.arg(tclose_metric_numeric)
TIL

2024-10-02 12:34 UTC, awunderground commented on R/disc_baseline.R
> +    }
Consider moving this from an anonymous function to a name function defined inside of `disc_baseline()`.

2024-10-02 12:34 UTC, awunderground commented on R/disc_baseline.R
> +  sens_metrics <- conf_w_key_ids %>%
Please unnest and break this up. For example, it is tough to follow because there is an anonymous function inside of an anonymous function.

2024-10-02 12:34 UTC, awunderground commented on R/disc_baseline.R
> +                  qid_prop <- c(table(x, exclude=NULL)) / nrow(gdf)
I also like this: `prop.table(table(c("a", "a", "b")))`

2024-10-02 12:34 UTC, awunderground commented on R/disc_baseline.R
> +                    )
Does this only allow for one metric to be calculated? What if I want "l1" and "l2"?

2024-10-02 12:34 UTC, awunderground commented on R/disc_baseline.R
> +      )
I don't think piped code inside of `list()` inside of `return()` is sufficiently clear.

2024-10-02 12:34 UTC, awunderground commented on tests/testthat/test-disc_baseline.R
Is it worth adding a test with made up data where we know the exact calculation for l1, l2, linf, ks, wass, etc.?

2024-10-04 13:39 UTC, jhseeman commented on tests/testthat/test-disc_baseline.R
added comments

2024-10-04 13:40 UTC, jhseeman commented on R/disc_baseline.R
> +      )
added comments

2024-10-09 11:13 UTC, awunderground approved these changes

2024-10-09 12:27 UTC, merged