Add `eval_data`
UrbanInstitute/syntheval pull request #90
Opened 2024-07-17 18:44 UTC by jhseeman

2024-07-22 17:29 UTC, jhseeman commented
── R CMD check results ──────────────────────────────────────────── syntheval 0.0.3 ────
Duration: 43s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

2024-07-25 20:39 UTC, awunderground requested changes
Very cool!

Did you run `devtools::document()` before building the package? The NAMESPACE should update with the addition of a function and a class.

2024-07-25 20:39 UTC, awunderground commented on R/eval_data.R
> +      stopifnot(all(purrr::map_lgl(synth_data, ~ inherits(.x, "postsynth"))))
Please include `.x` and `.f` as argument names in the call to `map_lgl()`.

2024-07-25 20:39 UTC, awunderground commented on R/eval_data.R
> +      synth_data <- purrr::map(synth_data, ~ .x$synthetic_data)
Please include `.x` and `.f` as argument names in the call to `map()`.

2024-07-25 20:39 UTC, awunderground commented on R/eval_data.R
> +      stopifnot(all(purrr::map_lgl(synth_data, ~ inherits(.x, "data.frame"))))
Please include `.x` and `.f` as argument names in the call to `map_lgl()`.

2024-07-25 20:39 UTC, awunderground commented on R/eval_data.R
> +      " replicate(s) \n")
Can we add the dimensions of the synthetic data too? Sometimes the synthetic data is much narrower and than `conf_data` and I think that would be useful to see.

2024-08-15 19:55 UTC, awunderground requested changes
*minor* changes requested!

2024-08-15 19:55 UTC, awunderground commented on R/eval_data.R
> +    stopifnot(identical(names(conf_data), names(holdout_data)))
I can think of cases where this may be a little problematic. For example, some variable is created for the synthesis that isn't present in the holdout data but isn't core to the evaluation. 

Perfect overlap is pretty strict!

2024-08-15 19:55 UTC, awunderground commented on R/eval_data.R
> +    synth_data <- synth_data$synthetic_data
Following the standard in RStudio, I'm swtiching from `$` to `[[]]`. I would write `synth_data[["synthetic_data"]]`

2024-08-15 19:55 UTC, awunderground commented on R/eval_data.R
If working with replicates, is it important that the replicates are the same dimensions?

2024-08-15 19:55 UTC, awunderground commented on R/eval_data.R
> +    synth_data <- synth_data$synthetic_data
Just FWIW!

2024-08-15 19:55 UTC, awunderground commented on R/eval_data.R
> +      dim(x$synth_data)[2],
Can we indent the last line by two spaces (or something) since it is the only row that belongs to the previous line. 

OLD:

```
Evaluation Data 
Confidential Data:  32  rows x  11  columns 
Synthetic Data:  1  replicate(s) 
32  rows x  11  columns 
```

NEW:

```
Evaluation Data 
Confidential Data:  32  rows x  11  columns 
Synthetic Data:  1  replicate(s) 
  32  rows x  11  columns 
```

2024-08-15 20:17 UTC, jhseeman commented on R/eval_data.R
> +    stopifnot(identical(names(conf_data), names(holdout_data)))
good call, removed

2024-08-15 20:17 UTC, jhseeman commented on R/eval_data.R
> +    synth_data <- synth_data$synthetic_data
Fixed

2024-08-15 20:18 UTC, jhseeman commented on R/eval_data.R
Depends on the context - this could also be randomized!

2024-08-15 20:18 UTC, jhseeman commented on R/eval_data.R
> +      dim(x$synth_data)[2],
Done

2024-08-15 20:40 UTC, awunderground approved these changes

2024-08-15 20:44 UTC, merged