Add multiple replicate membership inference
UrbanInstitute/syntheval pull request #91
Opened 2024-07-17 20:41 UTC by jhseeman

Draft for now pending discussion on #89 and #90

2024-08-15 21:20 UTC, awunderground requested changes
I left some in-line comments. I wonder if there is a way to use `nn_membership_inference()` twice.

2024-08-15 21:20 UTC, awunderground commented on R/disc_mit.R
> +      \(x, idx) {
`.x = ` and `.f = `.

2024-08-15 21:20 UTC, awunderground commented on R/disc_mit.R
> +    all_distances <- Reduce(c, synth_distances)
Any reason to use `Reduce()` instead of `purrr::reduce()`?

2024-08-15 21:20 UTC, awunderground commented on R/disc_mit.R
> +      \(.x) {
`.x = ` and `.f = `

2024-08-15 21:20 UTC, awunderground commented on R/disc_mit.R
> +    # for each record in the blended data, calculate the distance to the closest
Is there a way to reuse `nn_membership_inference()` here instead of repeating a lot of its logic?

2024-08-15 21:20 UTC, awunderground commented on R/disc_mit.R
> +        .data[["pseudo_probability"]]
Is there a name for this argument? It looks like it goes into `...`

2024-08-15 21:20 UTC, awunderground commented on R/disc_mit.R
> +        .data[["pseudo_probability"]]
R now gets weird about the `.data` pronoun. So I get these warnings:

```
Disaggregation returns tibble
Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
i Please use `all_of(var)` (or `any_of(var)`) instead of `.data[[var]]`
```

I'm not actually sure how to resolve this off of the top of my head.

2024-08-16 13:48 UTC, jhseeman commented on R/disc_mit.R
> +  } else {
Resolved using `eval_data`

2024-08-16 14:47 UTC, jhseeman commented
> I wonder if there is a way to use `nn_membership_inference()` twice.

Even though there's a fair amount of overlap between the one-replicate and multiple-replicate setting, there are enough places that differ where I decided it would cause more trouble to use the same helper function.

2024-08-23 16:16 UTC, awunderground reviewed
This is looking really good. I get one WARNING using check because the follow function isn't fully documented:

```
#' @export
is_eval_data <- function(x) {
  inherits(x, "eval_data")
}
```

Will this be resolved in the other PRs (acknowledging that these build on one another).

2024-09-10 13:06 UTC, jhseeman commented on R/disc_mit.R
fixed and included

2024-09-10 13:37 UTC, awunderground approved these changes

2024-09-10 13:42 UTC, merged