Discrete disclosure risk metric helper functions
UrbanInstitute/syntheval pull request #93
Opened 2024-07-31 21:38 UTC by jhseeman

2024-09-11 11:39 UTC, awunderground requested changes
The issue with `cut()` is major and needs a fix. Everything else is pretty minor.

2024-09-11 11:39 UTC, awunderground commented on R/disc_dd_helper.R
> +    keys <- keys
Why is this line necessary?

2024-09-11 11:39 UTC, awunderground commented on R/disc_dd_helper.R
> +    }
There is probably a clever way to replace this with `walk()` but it isn't necessary!

2024-09-11 11:39 UTC, awunderground commented on R/disc_dd_helper.R
> +  return(0)
`0` is a surprising value to return for a validation. Did you think about `TRUE`/`FALSE`?

2024-09-11 11:39 UTC, awunderground commented on R/disc_dd_helper.R
> +      )
It probably doesn't matter in this context, but growing vectors in R is very slow.

2024-09-11 11:39 UTC, awunderground commented on R/disc_dd_helper.R
> +    }
This entire section would benefit from better commenting. Why are you doing each of these steps?

2024-09-11 11:39 UTC, awunderground commented on R/disc_dd_helper.R
> +      )
Please include argument names.

2024-09-11 11:39 UTC, awunderground commented on R/disc_dd_helper.R
> +      )
`cut()` doesn't include the minimum values by default and instead introduces `NA`. Consider the following example using the `cars` data set:

```r
> orig_ed <- eval_data(
+   conf_data = cars, 
+   synth_data = cars
+ )
> 
> disc_ed1 <- prep_discrete_eval_data(
+   orig_ed,
+   col_map = list(
+     "speed" = list("k" = 2), 
+     "dist" = list("k" = 2)
+   )
+ )
> 
> head(disc_ed1[["conf_data"]])
     speed   dist
1     <NA>   <NA>
2     <NA> (2,61]
3 (4,14.5] (2,61]
4 (4,14.5] (2,61]
5 (4,14.5] (2,61]
6 (4,14.5] (2,61]
```

Please turn this into a test to ensure the function doesn't introduce additional `NA` values into the confidential data.

2024-09-11 11:39 UTC, awunderground commented on R/disc_dd_helper.R
> +      )
I *think* adding `include.lowest = TRUE` helps. 

```r
> x <- 1:10
> 
> cut(x = x, breaks = c(1, 5, 10))
 [1] <NA>   (1,5]  (1,5]  (1,5]  (1,5]  (5,10] (5,10] (5,10] (5,10] (5,10]
Levels: (1,5] (5,10]
> 
> cut(x = x, breaks = c(1, 5, 10), include.lowest = TRUE)
 [1] [1,5]  [1,5]  [1,5]  [1,5]  [1,5]  (5,10] (5,10] (5,10] (5,10] (5,10]
Levels: [1,5] (5,10]
```

2024-09-12 13:30 UTC, jhseeman commented on R/disc_dd_helper.R
> +    keys <- keys
it is not! good catch

2024-09-12 13:31 UTC, jhseeman commented on R/disc_dd_helper.R
> +  return(0)
I was using the linux exit code convention https://www.agileconnection.com/article/overview-linux-exit-codes but open to alternatives if you feel strongly another way

2024-09-12 13:33 UTC, jhseeman commented on R/disc_dd_helper.R
> +      )
yep, assuming syntheval users are not preparing egregiously wide tables for evaluation, pre-allocating the space for the vector would make a negligible difference. Can revisit if we choose to make this scalable (ex: incorporating Spark SQL or similar tools)

2024-09-12 13:39 UTC, jhseeman commented on R/disc_dd_helper.R
> +    }
flag for later: need to update this to consider `na.rm` logic!

2024-09-25 10:43 UTC, awunderground approved these changes
Good work.

2024-09-25 10:45 UTC, merged