add qid probability disclosure risk metrics
UrbanInstitute/syntheval pull request #99
Opened 2024-09-25 20:24 UTC by jhseeman

2024-10-02 12:02 UTC, awunderground requested changes
The code looks correct (except for the two lines I don't understand). 

Some of the syntax is very dense and tough to follow. I added some suggestions to make the code clearer.

2024-10-02 12:02 UTC, awunderground commented on tests/testthat/test-disc_qid_mi.R
> +    acs_eval[["n_rep"]]
I don't understand this code. Can you explain to me what's going on?

2024-10-04 12:05 UTC, jhseeman commented on R/disc_qid_mi.R
> +      ),
Fixed the formatting - also `dplyr::select(synth_id, key_id, raw_n, prop)` achieves the same outcome, but it will raise a `CHECK` warning when building the package because it can't treat the unquoted expressions as global variables

2024-10-04 12:26 UTC, jhseeman commented on R/disc_qid_mi.R
> +          prop_abserr_holdout = abs(
I precomputed it since the plots only use the absolute value of the errors, but it's not necessary! I will move the absolute value into the plotting functionality

2024-10-04 12:43 UTC, jhseeman commented on R/disc_qid_mi.R
> +                          qtiles = c(.5, .75, .9),
switched

2024-10-04 12:45 UTC, jhseeman commented on R/disc_qid_mi.R
> +        dplyr::filter(.data[["raw_n_conf"]] <= max_k),
yep, moved

2024-10-04 12:49 UTC, jhseeman commented on tests/testthat/test-disc_qid_mi.R
> +    acs_eval[["n_rep"]]
added comments

2024-10-09 11:11 UTC, awunderground approved these changes

2024-10-09 12:26 UTC, merged